# -*- coding: utf-8 -*-
"""line_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V3U2-clSZdcAGzOaygqIsKH0a98txOk8
"""

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage
import pya3rt

app = Flask(__name__)

linebot_api = LineBotApi("34Pwe99xm3nPN5Yw1DTt8o9fU1sjIFDO450n6NbwRPwxq+cLHLdfFKTEeY5ypagnCsvEOKJ4Gu81zwCJGOhyoVbDwdSgDb4WncTYbu+JSt9tjwGyJ8uWBd2G93rVcpcekxIhePy3tVvIa+qE3Aq4KAdB04t89/1O/w1cDnyilFU=")

handler = WebhookHandler("057301987e7123146bbc306b3afbd3a4")

@app.route("/hello")
def hello_world():
  return "Hello World!"

@app.route("/talk")
def talk():
  api_key = "DZZbgJRZHt1BE0YTVMekEQZqFY3PSBJn"
  cliant = pya3rt.TalkClient(api_key)
  reply_message = cliant.talk("こんにちは")
  return reply_message["results"][0]["reply"]

# 何かアクセスがあったときにまず応答
@app.route("/callback", methods=["POST"])
def callback():
  signature = request.headers["X-Line-Signature"]
  body = request.get_data(as_text=True)
  app.logger.info("Request body: " + body)
  try:
    handler.handle(body, signature)
  except InvalidSignatureError:
    abort(400)
  return "OK"

# メッセージが送られてきたときに返信,テキストを返す
@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
  ai_message = talk_ai(event.message.text)
  linebot_api.reply_message(event.reply_token, 
                             TextSendMessage(text=ai_message))
  # linebot_api.reply_message(event.reply_token, 
  #                            TextSendMessage(text="テストです．"))

def talk_ai(word):
  api_key = "DZZbgJRZHt1BE0YTVMekEQZqFY3PSBJn"
  cliant = pya3rt.TalkClient(api_key)
  reply_message = cliant.talk(word)
  return reply_message["results"][0]["reply"]

if __name__ == "__main__":
  app.run()